### ISSUE TITLE
Error inflating class <unknown>

### ISSUE THREAD

**Issue by dragitpro** [androidx/constraintlayout#567] opened 2022-04-17 07:27 UTC
Hello i'm triying to update the library to last version but since Version 2.0.0 , im facing an Error inflating class <unknown>, i dont have this problem in Version 2.0.0-rc1.

        View view = View.inflate(getBaseContext(),R.layout.activity_description, null);

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/constraintLayout2"
    android:background="?attr/colorBackgroundFloating"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:isScrollContainer="false">
	<FrameLayout
        android:id="@+id/main_media_frame"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/black"
        app:layout_constraintBottom_toTopOf="@+id/card_view"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">
		<com.google.android.exoplayer2.ui.StyledPlayerView
            android:id="@+id/exoplayer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="top"
            app:player_layout_id="@layout/exo_simple_player_view"
            app:controller_layout_id="@layout/exo_playback_control_view"/>
	</FrameLayout>
	<androidx.cardview.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:cardCornerRadius="4dp"
        app:cardElevation="4dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/main_media_frame">
		<androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/constraintLayout_card"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?attr/colorBackgroundFloating">
			<androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/source"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:layout_marginTop="2dp"
                android:fontFamily="@font/obel"
                android:gravity="center_horizontal"
                android:maxLines="1"
                android:text="@string/source"
                android:textColor="?attr/colorSecondary"
                android:textSize="12sp"
                app:layout_constraintBottom_toBottomOf="@+id/circleView"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
			<androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/circleView"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_marginStart="4dp"
                android:gravity="center_vertical"
                app:layout_constraintStart_toEndOf="@+id/source"
                app:layout_constraintTop_toTopOf="parent" />
			<androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/like"
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:layout_marginTop="8dp"
                android:layout_marginEnd="8dp"
                android:layout_marginBottom="8dp"
                app:layout_constraintBottom_toBottomOf="@+id/circleView"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
			<androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rvprog"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:background="?attr/colorBackgroundFloating"
                app:layout_constraintBottom_toTopOf="@id/adView2"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/circleView" />
			<ProgressBar
                android:id="@+id/progress_bar_loading_recycler_description"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginStart="75dp"
                android:layout_marginTop="75dp"
                android:layout_marginEnd="75dp"
                android:layout_marginBottom="75dp"
                android:indeterminateTint="?attr/colorAccent"
                app:layout_constraintBottom_toTopOf="@id/adView2"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/circleView" />
			<androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/programmenotavailable"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:gravity="center_horizontal"
                android:maxLines="2"
                android:textColor="?attr/colorSecondary"
                android:visibility="gone"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/circleView" />
			<androidx.appcompat.widget.LinearLayoutCompat
				xmlns:ads="http://schemas.android.com/apk/res-auto"
                android:id="@+id/adView2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_centerHorizontal="true"
                android:background="#00000000"
                ads:adSize="SMART_BANNER"
                ads:adUnitId="@string/adbannedescription"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent" />
			</androidx.constraintlayout.widget.ConstraintLayout>
		</androidx.cardview.widget.CardView>
	</androidx.constraintlayout.widget.ConstraintLayout>
```

>     Process: com.live.test, PID: 2398
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.live.test/com.live.test.gui.DescriptionActivity}: android.view.InflateException: Binary XML file line #2 in com.live.test:layout/activity_description: Binary XML file line #2 in com.live.test:layout/activity_description: Error inflating class <unknown>
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3786)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:233)
>         at android.app.ActivityThread.main(ActivityThread.java:8030)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
>      Caused by: android.view.InflateException: Binary XML file line #2 in com.live.test:layout/activity_description: Binary XML file line #2 in com.live.test:layout/activity_description: Error inflating class <unknown>
>      Caused by: android.view.InflateException: Binary XML file line #2 in com.live.test:layout/activity_description: Error inflating class <unknown>
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Constructor.newInstance0(Native Method)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
>         at android.view.LayoutInflater.createView(LayoutInflater.java:852)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
>         at android.view.View.inflate(View.java:26947)
>         at com.live.test.gui.DescriptionActivity.onCreate(DescriptionActivity.java:208)
>         at android.app.Activity.performCreate(Activity.java:8006)
>         at android.app.Activity.performCreate(Activity.java:7990)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3595)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3786)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:233)
>         at android.app.ActivityThread.main(ActivityThread.java:8030)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
>      Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0400e6 a=-1}
>         at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1025)
>         at android.content.res.TypedArray.getDrawable(TypedArray.java:1009)
>         at android.view.View.<init>(View.java:5586)
>         at android.view.ViewGroup.<init>(ViewGroup.java:708)
>         at android.view.ViewGroup.<init>(ViewGroup.java:704)
>         at android.view.ViewGroup.<init>(ViewGroup.java:700)
> 2022-04-17 09:12:16.637 2398-2398/com.live.test E/AndroidRuntime:     at androidx.constraintlayout.widget.ConstraintLayout.<init>(ConstraintLayout.java:567)
>         	... 25 more

**Comment by jafu888** [comment] 2022-04-18 18:09
I was able to get it to work with a different inflation pattern
 I suspect ConstraintLayout needs access to its parent now
 
 ```java
getLayoutInflater().inflate(  R.layout.activity_main, parentView, false);
```

I removed the ad and exoPlayer  (see below) but the crash was happening.

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/constraintLayout2"
    android:background="?attr/colorBackgroundFloating"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:isScrollContainer="false">
    <FrameLayout
        android:id="@+id/main_media_frame"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/black"
        app:layout_constraintBottom_toTopOf="@+id/card_view"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">
<!--        <com.google.android.exoplayer2.ui.StyledPlayerView-->
        <ImageView
            android:id="@+id/exoplayer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:src="@mipmap/ic_launcher"
            android:gravity="top"
            android:background="#464"/>
<!--            app:player_layout_id="@layout/exo_simple_player_view"-->
<!--            app:controller_layout_id="@layout/exo_playback_control_view"/>-->
    </FrameLayout>
    <androidx.cardview.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:cardCornerRadius="4dp"
        app:cardElevation="4dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/main_media_frame">
        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/constraintLayout_card"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?attr/colorBackgroundFloating">
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/source"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:layout_marginTop="2dp"
                android:gravity="center_horizontal"
                android:maxLines="1"
                android:text="noisdhf sd f sdf sd f sdf sdf sd f"
                android:textColor="?attr/colorSecondary"
                android:textSize="12sp"
                app:layout_constraintBottom_toBottomOf="@+id/circleView"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/circleView"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_marginStart="4dp"
                android:gravity="center_vertical"
                app:layout_constraintStart_toEndOf="@+id/source"
                app:layout_constraintTop_toTopOf="parent" />
            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/like"
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:layout_marginTop="8dp"
                android:layout_marginEnd="8dp"
                android:layout_marginBottom="8dp"
                app:layout_constraintBottom_toBottomOf="@+id/circleView"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rvprog"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:background="?attr/colorBackgroundFloating"
                app:layout_constraintBottom_toTopOf="@id/adView2"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/circleView" />
            <ProgressBar
                android:id="@+id/progress_bar_loading_recycler_description"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginStart="75dp"
                android:layout_marginTop="75dp"
                android:layout_marginEnd="75dp"
                android:layout_marginBottom="75dp"
                android:indeterminateTint="?attr/colorAccent"
                app:layout_constraintBottom_toTopOf="@id/adView2"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/circleView" />
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/programmenotavailable"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:gravity="center_horizontal"
                android:maxLines="2"
                android:textColor="?attr/colorSecondary"
                android:visibility="gone"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/circleView" />
            <androidx.appcompat.widget.LinearLayoutCompat
                xmlns:ads="http://schemas.android.com/apk/res-auto"
                android:id="@+id/adView2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_centerHorizontal="true"
                android:background="#00000000"

                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent" />
<!--                   ads:adSize="SMART_BANNER"
                ads:adUnitId="@string/adbannedescription"-->
        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.cardview.widget.CardView>
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by dragitpro** [comment] 2022-04-18 19:41
I bypassed that error with your code , but i got exactlly same one just a bit after on my code with recyclerview adapter for same error (same result with these 2ways). :

```
    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
        LayoutInflater inflater = (LayoutInflater) context.getSystemService( Context.LAYOUT_INFLATER_SERVICE );
        return new MyViewHolder(inflater.inflate(R.layout.item_channel,viewGroup,false));
        // OR  return new MyViewHolder(LayoutInflater.from(context).inflate(R.layout.item_channel, viewGroup, false));

    }
```


I also tried ::

```
   @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
        return new MyViewHolder(View.inflate(context, R.layout.item_channel, viewGroup));        
    }
```



Still have an error but a bit different : 
```

java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
        at android.view.View.measure(View.java:25671)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:466)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:134)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:278)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
        at android.view.View.measure(View.java:25671)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1656)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:601)
        at android.view.View.measure(View.java:25671)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
        at android.view.View.measure(View.java:25671)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25671)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25671)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
```

**Comment by dragitpro** [comment] 2022-05-01 09:38
I was using wrong context fixed with https://github.com/material-components/material-components-android/issues/1765

**Comment by oscar-ad** [comment] 2022-06-27 20:47
Sounds like it's working as intended then. Closing, but let us know if you still run into issues.

**Closed by oscar-ad** 2022-06-27 20:47 UTC
Labels: bug
